# Generated by Django 5.1 on 2026-06-09 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("google.com", "Google"), ("phone", "Phone")], max_length=32)),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firebase_identities",
                        to="identity.user",
                    ),
                ),
            ],
            options={
                "db_table": "firebase_identities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="firebaseidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"),
                name="identity_provider_subject_unique",
            ),
        ),
    ]
