# Generated by Django 5.1 on 2026-06-08 14:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_user_product_review')],
            },
        ),
    ]
