# Generated by Django 5.1 on 2026-06-08 14:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(unique=True)),
                ('tracking_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Tracking code must be 8-20 alphanumeric characters.', regex='^[A-Za-z0-9]{8,20}$')])),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], default='processing', max_length=10)),
                ('shipping_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_shipment_status'), models.Index(fields=['order_id'], name='idx_shipment_order_id')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipping.shipment')),
            ],
            options={
                'db_table': 'shipment_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
